### ISSUE TITLE
Ability to pan

### ISSUE THREAD

**Issue by mkofdwu** [octo-kumo/evil-er#4]
Currently, there does not seem to be any way to pan across the diagram other than zooming in and out. It would greatly improve the user experience to implement a panning function (for example with space + mouse drag)

**Comment by Fasnon** [comment]
I agree, as a frequent user of this app, which I use instead of say Powerpoint, this would greatly benefit my life, my workflow, saving a lot of time.

**Comment by mkofdwu** [comment]
Never mind, its right click and drag 💀
